# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(default='work', max_length=255),
            preserve_default=False,
        ),
    ]
