# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20171120_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='exam_app.User'),
        ),
    ]
