# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_auto_20171120_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='user',
        ),
    ]
