# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_auto_20171120_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
