# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_auto_20171120_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
