# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='exam_app.User'),
            preserve_default=False,
        ),
    ]
